title : Luk치코 Zapletal
tagline: engineer in pyjama
permalink: /:categories/:year/:month/:title.html
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
safe: true
production_url: http://lukas.zapletalovi.com
markdown: kramdown
author:
  name: Luk치코 Zapletal
analytics:
  mixpanel_token: 
