title : Luk치코 Zapletal
tagline: engineer in pyjama
permalink: /:categories/:year/:month/:title.html
exclude: ['Rakefile', 'README.md', 'config.rb']
safe: true
production_url: https://lukas.zapletalovi.com
enforce_ssl: lukas.zapletalovi.com
markdown: kramdown
highlighter: rouge
author:
  name: Luk치코 Zapletal
