# Theme docs at https://main--gokarna-hugo.netlify.app/posts/
theme = "gokarna"

title = 'Lukáš Zapletal'
baseURL = 'https://lukas.zapletalovi.com'
languageCode = 'en-us'
defaultContentLanguage = "en"
enableRobotsTXT = true

[menu]
[[menu.main]]
identifier = "Posts"
url = "/posts/"
name = "Posts"
weight = 5

[[menu.main]]
identifier = "Me"
url = "/me/"
name = "About me"
weight = 10

[[menu.main]]
identifier = "contact"
url = "/contact/"
name = "Contact"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "github"
# https://feathericons.com
pre = "<span data-feather='github'></span>"
url = "https://github.com/lzap"
weight = 40

[[menu.main]]
identifier = "mastodon"
# https://simpleicons.org (copy, paste, add width/height)
pre = '<svg role="img" height="20" width="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Mastodon</title><path d="M23.268 5.313c-.35-2.578-2.617-4.61-5.304-5.004C17.51.242 15.792 0 11.813 0h-.03c-3.98 0-4.835.242-5.288.309C3.882.692 1.496 2.518.917 5.127.64 6.412.61 7.837.661 9.143c.074 1.874.088 3.745.26 5.611.118 1.24.325 2.47.62 3.68.55 2.237 2.777 4.098 4.96 4.857 2.336.792 4.849.923 7.256.38.265-.061.527-.132.786-.213.585-.184 1.27-.39 1.774-.753a.057.057 0 0 0 .023-.043v-1.809a.052.052 0 0 0-.02-.041.053.053 0 0 0-.046-.01 20.282 20.282 0 0 1-4.709.545c-2.73 0-3.463-1.284-3.674-1.818a5.593 5.593 0 0 1-.319-1.433.053.053 0 0 1 .066-.054c1.517.363 3.072.546 4.632.546.376 0 .75 0 1.125-.01 1.57-.044 3.224-.124 4.768-.422.038-.008.077-.015.11-.024 2.435-.464 4.753-1.92 4.989-5.604.008-.145.03-1.52.03-1.67.002-.512.167-3.63-.024-5.545zm-3.748 9.195h-2.561V8.29c0-1.309-.55-1.976-1.67-1.976-1.23 0-1.846.79-1.846 2.35v3.403h-2.546V8.663c0-1.56-.617-2.35-1.848-2.35-1.112 0-1.668.668-1.67 1.977v6.218H4.822V8.102c0-1.31.337-2.35 1.011-3.12.696-.77 1.608-1.164 2.74-1.164 1.311 0 2.302.5 2.962 1.498l.638 1.06.638-1.06c.66-.999 1.65-1.498 2.96-1.498 1.13 0 2.043.395 2.74 1.164.675.77 1.012 1.81 1.012 3.12z"/></svg>'
url = "https://mastodon.social/@lzap"
weight = 50

[[menu.main]]
identifier = "twitter"
pre = "<span data-feather='twitter'></span>"
url = "https://twitter.com/lzap"
weight = 60

[[menu.main]]
identifier = "buymeacoffee"
pre = "<span data-feather='coffee'></span>"
url = "https://www.buymeacoffee.com/lzap"
weight = 70

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/atom.xml"
weight = 80

[params]
# URL for the avatar on homepage
#avatarURL = "/images/avatar_rh_512.jpg"
avatarURL = "/images/avatar_rh_256.avif"

# Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
avatarSize = "size-l"

# Description to display on homepage
description = "engineer in pyjama"

# Accent color is displayed when you hover over <a> tags
accentColor = "#FF4D4D"

# You can use this to inject any HTML in the <head> tag.
# Ideal usecase for this is to import custom js/css or add your analytics snippet
customHeadHTML = '''
<!-- analytics, CSP and RSS alternate -->
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline' static.cloudflareinsights.com; connect-src 'self' cloudflareinsights.com; img-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self';" />
<script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "e0a5b1d968fe4fc1942644c21fcf78dd"}'></script>
<link rel="alternate" type="application/rss+xml" href="https://lukas.zapletalovi.com/atom.xml" title="Lukas Zapletal's blog" />
<link rel="me" href="https://mastodon.social/@lzap" />
<meta name="google-site-verification" content="Ifsr98Ygg7L5HGgZxibL3t2m15RdWi1hvOjr-t1FJl4" />
<meta name="google-site-verification" content="5tQ8W4BRim8RCoroRu-GlGa1YAy05riDN1uZJ7fz2Xk" />
'''

# Keywords relevant for SEO
metaKeywords = ["blog", "lzap", "lukáš", "zapletal", "linux", "tech"]

# If you want to display posts on the homepage, the options are
# "popular" (order posts by weight), "recent" (order posts by date)
# or "" (do not display, default option)
showPostsOnHomePage = "recent"

# Footer text
footer = "Lukáš Zapletal, CC BY 4.0"

# Social stuff, icons from https://simpleicons.org (/static/icons/)
socialIcons = [
	{name = "mastodon", url = "https://mastodon.social/@lzap"},
	{name = "twitter", url = "https://twitter.com/lzap"},
	{name = "linkedin", url = "https://www.linkedin.com/in/lukaszapletal"},
	{name = "github", url = "https://www.github.com/lzap"},
	{name = "stackoverflow", url = "https://stackoverflow.com/users/299204/lzap"},
	{name = "email", url = "mailto:lukas-x@zapletalovi.com?subject=Remove -x from my email"}
]

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 3
ordered = false

[services.rss]
 limit = 20

# change RSS from the default index.xml to atom.xml
[outputs]
home = [ "RSS", "HTML"]
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"
